# Generated by Django 6.0.3 on 2026-04-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Симптом')),
            ],
            options={
                'verbose_name': 'Симптом',
                'verbose_name_plural': 'Симптоми',
            },
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Хвороба', 'verbose_name_plural': 'Хвороби'},
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(upload_to='diseases/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва хвороби'),
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='diseases', to='diseases.symptom', verbose_name='Симптоми'),
        ),
    ]
